image: registry.gitlab.com/charts/alpine-helm

stages:
  - test
  - release

lint:
  stage: test
  script:
    - helm lint .
  except:
    - master

release-bump:
  stage: release
  script:
    - git checkout master
    - git pull
    - git merge --no-commit $CI_COMMIT_SHA
    - helm plugin install https://github.com/mbenabda/helm-local-chart-version
    - helm local-chart-version set 69.69.69
    - git add .
    - git commit -m "chore(release): 69.69.69"

release-chart:
  stage: release
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.craiggardener.uk/api/v4/projects/1/trigger/pipeline
  only:
    - master
