image: registry.gitlab.com/charts/alpine-helm

stages:
  - test
  - release

lint:
  stage: test
  script:
    - helm lint .
  except:
    - master

release-bump:
  stage: release
  script:
    - mkdir -p ~/.ssh
    - echo "$GITLAB_CI_SSH_KEY" > ~/.ssh/id_rsa
    - ssh-keyscan gitlab.craiggardener.uk > ~/.ssh/known_hosts
    - apk add --no-cache --update openssh-client perl
    - git remote set-url --push origin $(echo $CI_REPOSITORY_URL | perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#')
    - git config --global user.email "gitlab-ci@craiggardener.uk"
    - git config --global user.name "GitLab CI"
    - git checkout master
    - git pull
    - git merge --no-commit $CI_COMMIT_SHA
    - touch example3.txt
    - git add .
    - git commit -m 'RELEASE 69.69.69'
    - git push

release-chart:
  stage: release
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.craiggardener.uk/api/v4/projects/1/trigger/pipeline
  only:
    - master
