image: registry.gitlab.com/charts/alpine-helm

stages:
  - test
  - release

lint:
  stage: test
  script:
    - helm lint .
  except:
    - master

semantic-release:
  stage: release
  image: node:8
  script:
    - npm -g install semantic-release @semantic-release/changelog @semantic-release/exec @semantic-release/git @semantic-release/gitlab
    - semantic-release
  only:
    - develop

release-chart:
  stage: release
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.craiggardener.uk/api/v4/projects/1/trigger/pipeline
  only:
    - master
